package com.saurabh.entity.records;

import com.saurabh.entity.attendence.AttendanceOfLeave;
import com.saurabh.entity.employee.Employee;

import java.util.List;

/**
 * Created by AroraA on 09-02-2016.
 */

public class EmployeeSalesforce extends Employee {
	final long serialVersionUID = 1L;
	/**
	 * the object of the Attendance of leave which
	 */
	private List<AttendanceOfLeave> attendanceOfLeaveList;

	public EmployeeSalesforce() {
	}

	/**
	 * EmployeeSalesforceDetails constructor that take following arguments
	 *
	 * @param empId                 The Employee Ids generated by Reval India for its employee
	 *                              [Unique for each employee in India]
	 * @param name                  The name of the Employee in Reval India
	 * @param attendanceOfLeaveList The overall details of attendance record read
	 *                              from the Salesforce File.
	 */
	public EmployeeSalesforce(String empId, String name, List<AttendanceOfLeave> attendanceOfLeaveList) {
		super.setEmpId(empId);
		super.setName(name);
		this.attendanceOfLeaveList = attendanceOfLeaveList;
	}

	public List<AttendanceOfLeave> getAttendanceOfLeaveList() {
		return attendanceOfLeaveList;
	}

	public void setAttendanceOfLeaveList(List<AttendanceOfLeave> attendanceOfLeaveList) {
		this.attendanceOfLeaveList = attendanceOfLeaveList;
	}

	/**
	 * Method to display the contents read till reading of the Financial-Force
	 * file
	 */
	@Override
	public String toString() {
		return "EmployeeSalesforceDetails{\n" +
				super.toString() + "\n" +
				", " + attendanceOfLeaveList +
				'}';
	}
}
